### ISSUE TITLE
Hanging crash in v1.4.1

### ISSUE THREAD

**Issue by xenoflot** [MattDahEpic/MDECore1.8#19] opened 2016-11-30 23:44 UTC
Hi,

Added MDECore 1.4.1 to my pack today.
Started the client, new world, open world... hangs. 
Technic console shows a crashlog but java is refusing to shut down :-)
Swapping back to MDECore 1.3 and I'm able to get into the world without error.

http://pastebin.com/VAjRtRK1
This crash report is awfully similar to the one I got when I let a 1.11 mod slip into the pack. 
Is 1.4.1 incorrectly flagged as 1.10.2 compatible?
Did I derp?

**Comment by MattDahEpic** [comment] 2016-11-30 23:58
Duplicate of #17, stay reverted for now.

**Closed as completed by MattDahEpic** 2016-11-30 23:58 UTC
Labels: duplicate
